Parameters:
##Comes in from our template configs like dev.json
  Environment:
    Type: String
    AllowedValues: [devxyzbs, qaxyzbs, pilotxyzbs, prodxyzbs]##Passed in from codepipeline
  BuildObjectKey:
    Type: String
Resources:
  MyLambdaLayer:
   Type: AWS::S3::Bucket
   Properties:
      BucketName: !Ref Environment
