Parameters:
##Comes in from our template configs like dev.json
  Environment:
    Type: String
    AllowedValues: [dev, qa, pilot, prod]##Passed in from codepipeline
  BuildObjectKey:
    Type: String
Resources:
  MyLambdaLayer:
   Type: AWS::Lambda::LayerVersion
   Properties:
     CompatibleRuntimes:
        - python3.7
     Content:
       S3Bucket: codepipeline-us-east-1-664598695354
       S3Key: !Sub ${BuildObjectKey}.zip    ##Description changes to MYLayer TIMESTAMP.ZIP
     Description: !Sub Mylayer ${BuildObjectKey}
     LayerName: !Sub ${Environment}-My-Layer
